
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuffypxwjhtmivcgryqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZmZ5cHh3amh0bWl2Y2dyeXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDY4NDksImV4cCI6MjA2MjE4Mjg0OX0.t8NIaMmnBrUISxaVjr8-Np19c82qWVcfjLAExYMGKCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
