
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxnmjfdhwsfmgvajmudc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4bm1qZmRod3NmbWd2YWptdWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxODA5NDUsImV4cCI6MjA3ODc1Njk0NX0.ztA1wsdRhJx-fapd9cBvf4gBBEoAAHOX11M80g6xRuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
